services:
  server:
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - 8080:8080 # アプリケーションポート
      - 40000:40000 # デバッガーポート
    command: dlv debug --listen=:40000 --headless=true --api-version=2 --accept-multiclient --continue
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: mysql
    restart: always
    container_name: mysql_todo_db
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 13306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
