services:
  server:
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/tmp # tmpディレクトリをマウントから除外
      - /tmp # システムのtmpディレクトリをマウントから除外

  db:
    image: mysql
    restart: always
    container_name: mysql_todo_db
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 13306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
