name: todo_flutter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  retrofit:
  dio:
  simple_logger:
  json_annotation:
  freezed_annotation:
  hooks_riverpod:
  flutter_hooks:
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:
  build_runner:
  json_serializable:
  freezed:
  flutter_lints: ^2.0.0
  widgetbook_generator: ^3.8.0

flutter:
  uses-material-design: true
